### PR TITLE
feat(http-manager)!: default to configurable pooling connection manager

### PR DESCRIPTION
**Pull request by dargmuesli**
Adds one commit to @gahisee's PR #375, which aligns the builder pattern so that it matches way it's used throughout this project: allowing the connection manager to be configurable. It also lets the connection manager default to a pooling connection manager so that most users don't face issue #383.

This is a breaking change (which is not an issue for me, those occur rarely) as the `connectTimeout` `ConnectionConfig` cannot be set anymore as is. Instead, a (basic) connection manager having that `ConnectionConfig` would need to be set now if it's needed to be kept.

@gahisee @Selbi182 @linde9821 please tell me what you think, I'd release a release candidate for this.
@gahisee your pull request would be merged automatically as well when this one is merged as this PR builds on top of yours so all your stats will be kept. I just thought it's a good idea to have this PR open to see the proposed changes more clearly when comparing against `master` :bulb:

### CODE REVIEW

**Review by gahisee — COMMENTED** [review]
looks fine to me.

**Comment by Selbi182** [comment]
Got nothing to add either, looks good!

I will give the RC a full spin soonish. If I don't report back, assume everything is working fine :D

**Comment by linde9821** [comment]
Tested `9.0.0-RC1` in my project. It solved the issue :)

**Comment by dargmuesli** [comment]
Thank you for the feedback! :rocket:

**Pull request merged**
