### PR TITLE
refactor: add constant and remove magic numbers

### PR DESCRIPTION
**Pull request by aSTRonuun**
Hello everyone, I'm submitting this refactor to learn how to contribute to open source projects at the same time as I study "code smells" and I analyzed this and found this improvement

[Magic Number Problem
](https://refactoring.guru/replace-magic-number-with-symbolic-constant) - By Refactoring Guru

In this refactoring technique, it is recommended to replace magic numbers or random values with constant symbols to improve readability

### CODE REVIEW

**Review by dargmuesli — COMMENTED** [review]
:+1: as it is crucial to keep this code's functionality which is not directly intuitive, it would make much sense to add a unit test which checks if the unmodified code yields the same output as the code changed as done here. Could you add such a test?

**Comment by aSTRonuun** [comment]
Ok, make sense for me... I can to do this

**Comment by dargmuesli** [comment]
Hey @aSTRonuun, why did you close this PR?

**Comment by aSTRonuun** [comment]
Hello @dargmuesli, the contributions are already in master with unit tests sent a few days ago, I think the PR is no longer necessary... i want to open news refactors

**Comment by dargmuesli** [comment]
> the contributions are already in master

Partly. Constants like `SHIFT_16` are not included as of now.

**Comment by aSTRonuun** [comment]
Ok, i will update this PR to resolve conflicts and open again

**Pull request closed without merging**
