### PR TITLE
Backward compatibility

### PR DESCRIPTION
**Pull request by gahisee**
for backward compatibility, now using usePoolingConnectionManager boolean
and restored previous SpotifyApi.build() with no parameter

### CODE REVIEW

**Comment by gahisee** [comment]
Sorry but this is my first time at this.
I made the second push but was not sure how to bring it to your attention.
Finally i made another branch to ensure backward compatibilty; i.e.
No change to SpotifyApi.build.
This is hopefully the last push. And i would think this pull request should be different from the first.


On December 6, 2023, at 2:35 PM, Jonas Thelemann ***@***.***> wrote:

It appears to me that opening a new PR wasn't necessary as the previous PR is updated to include the same changes. Am I correct? If so, we can close this PR.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.￼Message ID: ***@***.***>

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/spotify-web-api-java/spotify-web-api-java/pull/376#issuecomment-1843566463">https://github.com/spotify-web-api-java/spotify-web-api-java/pull/376#issuecomment-1843566463</a>", "url": "<a href="https://github.com/spotify-web-api-java/spotify-web-api-java/pull/376#issuecomment-1843566463">https://github.com/spotify-web-api-java/spotify-web-api-java/pull/376#issuecomment-1843566463</a>", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by dargmuesli** [comment]
No problem, thank you for contributing! As you can see in the "Commits" tab of both pull requests both branches point to the same commit, so I think this PR can be closed. Whenever you push to a branch for which you opened a PR, the PR updates automatically to include all recent changes :)

**Comment by dargmuesli** [comment]
Ah, and regarding attention: I am being notified about all changes, so I'll get to it as soon as I have time. Also you are welcome to add comments at any time, I'll be happy to reply.

**Comment by gahisee** [comment]
This PR was not necessary as all commits applied to the original PR.

**Pull request closed without merging**
