### PR TITLE
feat(track): correct type for recommendations and play-history

### PR DESCRIPTION
**Pull request by oemel09**
... and also play-history.

Spotify returns more information than available via `SimplifiedTrack`.
I need e. g. the release date which is returned by Spotify but not mapped to a `SimplifiedTrack`

### CODE REVIEW

**Comment by dargmuesli** [comment]
Hey there, thank you for the PR! Currently I'm unable to find a specification for objects that are returned by the API. This object specification has been available once, but seemingly vanished. Maybe you know a place for their specification? It was listed under https://developer.spotify.com/web-api/object-model/ in the past.

I'd like to make those changes for all places they belong at once so that the wrapper stays consistent to an API version state, so I'd first like to find a specification which can be used in that regard. Also I'm very busy until the end of the month, so I won't be able to work on that myself right now.

**Comment by oemel09** [comment]
I'm not really sure what kind of specification you're referring to.
What I found is that the [reference for the get recommendations endpoint](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-recommendations) still says, that a simplified track will be returned.
But when executing the call, it returns a track which contains the full album information and other info not available in a simplified track object.

The reference for recently played tracks is very vague, it says:
> items, array of objects - The requested data.
But obviously when executing the call it also returns e. g. album information of recently played tracks

**Comment by dargmuesli** [comment]
Hmm, ok. Do you think the simplified object contains more data now across all endpoints or is the recommendation endpoint returning a full object now?

It seems like the API's object model documentation is not available any more, a pity.

**Comment by dargmuesli** [comment]
I started an issue in the Spotify developer forum about the problem mentioned: https://community.spotify.com/t5/Spotify-for-Developers/Revive-the-Object-Model-Specification/td-p/5368580

**Review by dargmuesli — APPROVED** [review]
Seems like Spotify updated their documentation for those endpoints. Sadly, the general object model specification still remains unavailable.

I've updated the fixtures.

**Pull request merged**
